kategorias: []
orijenes:
  - Jeneral
linguas:
  - ebreo
gramatika:
  - verb
  - noun
  - NA
gender:
  - feminine
  - masculine
  - both
  - NA
numero:
  - singular
  - plural
verbos-iregolares: []
pajinas: []
listas:
  sezones: []
tiempos:
  - prezente
pronombres:
  - yo
  - tu
  - el
  - mozotros
  - vozotros
  - eyos

