name: CI

on:
  push:
#  schedule:
#    - cron: '9 * * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test code
    steps:
    - name: Generate HTML

    - name: Checkout this repo
      uses: actions/checkout@v2

    - name: Checkout the ladino-diksionaryo-data
      uses: actions/checkout@v2
      with:
        repository: 'szabgab/ladino-diksionaryo-data'
        path: ladino-diksionaryo-data

    - name: Checkout the  LibreLingo-Judeo-Spanish-from-English repo
      uses: actions/checkout@v2
      with:
        repository: 'szabgab/LibreLingo-Judeo-Spanish-from-English'
        path: LibreLingo-Judeo-Spanish-from-English

    - name: Install dependencies
      run: |
          python -V
          pip install -r requirements.txt
          pip install pytest

    - name: Run tests
      run: |
          pytest -sv test_generate.py

  generate:
    runs-on: ubuntu-latest
    name: Generate HTML

    steps:
    - name: Generate HTML
      env:
         PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        curl -X POST \
             -H "Authorization: token $PERSONAL_ACCESS_TOKEN" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/szabgab/ladino-diksionaryo-generated/actions/workflows/ci.yml/dispatches \
             -d '{"ref":"main"}' | tee out.txt
        if [ -s out.txt ]
        then
            exit 1
        else
            exit 0
        fi


